//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("icrm.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string Account_Settings {
            get {
                return ResourceManager.GetString("Account_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Department.
        /// </summary>
        public static string Add_Department {
            get {
                return ResourceManager.GetString("Add_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Department User.
        /// </summary>
        public static string Add_department_user {
            get {
                return ResourceManager.GetString("Add_department_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Email.
        /// </summary>
        public static string Add_Email {
            get {
                return ResourceManager.GetString("Add_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Icrm Agent.
        /// </summary>
        public static string Add_Icrm_Agent {
            get {
                return ResourceManager.GetString("Add_Icrm_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Religion.
        /// </summary>
        public static string add_religion {
            get {
                return ResourceManager.GetString("add_religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Search/Update User.
        /// </summary>
        public static string Add_Search_Update_user {
            get {
                return ResourceManager.GetString("Add_Search_Update_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string Add_user {
            get {
                return ResourceManager.GetString("Add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin/Category.
        /// </summary>
        public static string Admin_Category {
            get {
                return ResourceManager.GetString("Admin_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tickets.
        /// </summary>
        public static string All_Tickets {
            get {
                return ResourceManager.GetString("All_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appreciations.
        /// </summary>
        public static string Appreciations {
            get {
                return ResourceManager.GetString("Appreciations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Complaints.
        /// </summary>
        public static string Assigned_Complaints {
            get {
                return ResourceManager.GetString("Assigned_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for Chat.
        /// </summary>
        public static string Available_for_Chat {
            get {
                return ResourceManager.GetString("Available_for_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge No.
        /// </summary>
        public static string Badge_No {
            get {
                return ResourceManager.GetString("Badge_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band List.
        /// </summary>
        public static string Band_list {
            get {
                return ResourceManager.GetString("Band_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bands.
        /// </summary>
        public static string Bands {
            get {
                return ResourceManager.GetString("Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Phone No.
        /// </summary>
        public static string Business_phone_no {
            get {
                return ResourceManager.GetString("Business_phone_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        public static string Category_List {
            get {
                return ResourceManager.GetString("Category_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Category_name {
            get {
                return ResourceManager.GetString("Category_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string Change_Language {
            get {
                return ResourceManager.GetString("Change_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Action.
        /// </summary>
        public static string Choose_Action {
            get {
                return ResourceManager.GetString("Choose_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string Choose_Language {
            get {
                return ResourceManager.GetString("Choose_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Chat.
        /// </summary>
        public static string Close_Chat {
            get {
                return ResourceManager.GetString("Close_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Complaints.
        /// </summary>
        public static string Closed_Complaints {
            get {
                return ResourceManager.GetString("Closed_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment field Should  be empty.
        /// </summary>
        public static string Comment_field_Should_be_empty {
            get {
                return ResourceManager.GetString("Comment_field_Should_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Field Should not be empty.
        /// </summary>
        public static string Comment_Field_Should_not_be_empty {
            get {
                return ResourceManager.GetString("Comment_Field_Should_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string Cost_Center {
            get {
                return ResourceManager.GetString("Cost_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bands.
        /// </summary>
        public static string Create_bands {
            get {
                return ResourceManager.GetString("Create_bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string Create_Category {
            get {
                return ResourceManager.GetString("Create_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Department.
        /// </summary>
        public static string Create_department {
            get {
                return ResourceManager.GetString("Create_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Employee Class.
        /// </summary>
        public static string Create_employee_class {
            get {
                return ResourceManager.GetString("Create_employee_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Employer Type.
        /// </summary>
        public static string Create_emplyer_type {
            get {
                return ResourceManager.GetString("Create_emplyer_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Escalation Users.
        /// </summary>
        public static string Create_escalation_user {
            get {
                return ResourceManager.GetString("Create_escalation_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ethnicities.
        /// </summary>
        public static string Create_ethinicities {
            get {
                return ResourceManager.GetString("Create_ethinicities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Event Reasons.
        /// </summary>
        public static string Create_event_reasons {
            get {
                return ResourceManager.GetString("Create_event_reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Feedback Type.
        /// </summary>
        public static string Create_feedback_type {
            get {
                return ResourceManager.GetString("Create_feedback_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Gender.
        /// </summary>
        public static string Create_gender {
            get {
                return ResourceManager.GetString("Create_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job Title.
        /// </summary>
        public static string create_job_title {
            get {
                return ResourceManager.GetString("create_job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Locations.
        /// </summary>
        public static string Create_locations {
            get {
                return ResourceManager.GetString("Create_locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Nationality.
        /// </summary>
        public static string Create_nationality {
            get {
                return ResourceManager.GetString("Create_nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Position.
        /// </summary>
        public static string Create_position {
            get {
                return ResourceManager.GetString("Create_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Priorities.
        /// </summary>
        public static string create_priorities {
            get {
                return ResourceManager.GetString("create_priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sub Location.
        /// </summary>
        public static string Create_Sub_Location {
            get {
                return ResourceManager.GetString("Create_Sub_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ticket.
        /// </summary>
        public static string Create_Ticket {
            get {
                return ResourceManager.GetString("Create_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Vendor.
        /// </summary>
        public static string Create_vendor {
            get {
                return ResourceManager.GetString("Create_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string Created_Date {
            get {
                return ResourceManager.GetString("Created_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Locations.
        /// </summary>
        public static string Creating_Locations {
            get {
                return ResourceManager.GetString("Creating_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Religions.
        /// </summary>
        public static string Creating_religions {
            get {
                return ResourceManager.GetString("Creating_religions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Tickets By HR.
        /// </summary>
        public static string Creating_Tickets_By_HR {
            get {
                return ResourceManager.GetString("Creating_Tickets_By_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Tickets by Icrm Agent.
        /// </summary>
        public static string Creating_Tickets_by_Icrm_Agent {
            get {
                return ResourceManager.GetString("Creating_Tickets_by_Icrm_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department List.
        /// </summary>
        public static string Department_List {
            get {
                return ResourceManager.GetString("Department_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string Department_name {
            get {
                return ResourceManager.GetString("Department_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department should be Empty.
        /// </summary>
        public static string Department_should_be_Empty {
            get {
                return ResourceManager.GetString("Department_should_be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string Dont_have_an_account {
            get {
                return ResourceManager.GetString("Dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download APK.
        /// </summary>
        public static string Download_APK {
            get {
                return ResourceManager.GetString("Download_APK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Attachment.
        /// </summary>
        public static string Download_Attachment {
            get {
                return ResourceManager.GetString("Download_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        public static string Email_Id {
            get {
                return ResourceManager.GetString("Email_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Class.
        /// </summary>
        public static string Employee_Class {
            get {
                return ResourceManager.GetString("Employee_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Class List.
        /// </summary>
        public static string employee_class_list {
            get {
                return ResourceManager.GetString("employee_class_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        public static string Employee_Details {
            get {
                return ResourceManager.GetString("Employee_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id.
        /// </summary>
        public static string Employee_Id {
            get {
                return ResourceManager.GetString("Employee_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id not found.
        /// </summary>
        public static string Employee_Id_not_found {
            get {
                return ResourceManager.GetString("Employee_Id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string Employee_Name {
            get {
                return ResourceManager.GetString("Employee_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Type.
        /// </summary>
        public static string Employer_Type {
            get {
                return ResourceManager.GetString("Employer_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Type List.
        /// </summary>
        public static string Employer_type_list {
            get {
                return ResourceManager.GetString("Employer_type_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Employee ID.
        /// </summary>
        public static string Enter_Employee_ID {
            get {
                return ResourceManager.GetString("Enter_Employee_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Location Name.
        /// </summary>
        public static string Enter_Location_Name {
            get {
                return ResourceManager.GetString("Enter_Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sub Location Name.
        /// </summary>
        public static string Enter_Sub_Location_Name {
            get {
                return ResourceManager.GetString("Enter_Sub_Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string Enter_your_email {
            get {
                return ResourceManager.GetString("Enter_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Enter_your_password {
            get {
                return ResourceManager.GetString("Enter_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalation User List.
        /// </summary>
        public static string Escalation_user_list {
            get {
                return ResourceManager.GetString("Escalation_user_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalation Users.
        /// </summary>
        public static string Escalation_Users {
            get {
                return ResourceManager.GetString("Escalation_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicities.
        /// </summary>
        public static string Ethnicities {
            get {
                return ResourceManager.GetString("Ethnicities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicities List.
        /// </summary>
        public static string ethnicities_list {
            get {
                return ResourceManager.GetString("ethnicities_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Reason.
        /// </summary>
        public static string Event_Reason {
            get {
                return ResourceManager.GetString("Event_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Reason List.
        /// </summary>
        public static string Event_reason_list {
            get {
                return ResourceManager.GetString("Event_reason_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Reasons.
        /// </summary>
        public static string Event_reasons {
            get {
                return ResourceManager.GetString("Event_reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string Export_To_Excel {
            get {
                return ResourceManager.GetString("Export_To_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback/Complaint.
        /// </summary>
        public static string Feedback_Complaint {
            get {
                return ResourceManager.GetString("Feedback_Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Type.
        /// </summary>
        public static string Feedback_Type {
            get {
                return ResourceManager.GetString("Feedback_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Types.
        /// </summary>
        public static string Feedback_types {
            get {
                return ResourceManager.GetString("Feedback_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered By Employee Id.
        /// </summary>
        public static string Filtered_By_employeeid {
            get {
                return ResourceManager.GetString("Filtered_By_employeeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Escalation User.
        /// </summary>
        public static string first_escalation_user {
            get {
                return ResourceManager.GetString("first_escalation_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward/Create.
        /// </summary>
        public static string Forward_Create {
            get {
                return ResourceManager.GetString("Forward_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Email CC.
        /// </summary>
        public static string Forward_Email_CC {
            get {
                return ResourceManager.GetString("Forward_Email_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarded.
        /// </summary>
        public static string Forwarded {
            get {
                return ResourceManager.GetString("Forwarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender List.
        /// </summary>
        public static string Gender_list {
            get {
                return ResourceManager.GetString("Gender_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icrm Agent.
        /// </summary>
        public static string Icrm_Agent {
            get {
                return ResourceManager.GetString("Icrm_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiries.
        /// </summary>
        public static string Inquiries {
            get {
                return ResourceManager.GetString("Inquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Job_Title {
            get {
                return ResourceManager.GetString("Job_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title List.
        /// </summary>
        public static string Job_Title_List {
            get {
                return ResourceManager.GetString("Job_Title_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Jobtitle {
            get {
                return ResourceManager.GetString("Jobtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title List.
        /// </summary>
        public static string Jobtitle_list {
            get {
                return ResourceManager.GetString("Jobtitle_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Users.
        /// </summary>
        public static string List_Users {
            get {
                return ResourceManager.GetString("List_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Group.
        /// </summary>
        public static string Location_Group {
            get {
                return ResourceManager.GetString("Location_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location List.
        /// </summary>
        public static string Location_list {
            get {
                return ResourceManager.GetString("Location_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string Location_name {
            get {
                return ResourceManager.GetString("Location_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Middle_name {
            get {
                return ResourceManager.GetString("Middle_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality List.
        /// </summary>
        public static string Nationality_list {
            get {
                return ResourceManager.GetString("Nationality_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result.
        /// </summary>
        public static string No_result {
            get {
                return ResourceManager.GetString("No_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On date Criteria.
        /// </summary>
        public static string On_date_Criteria {
            get {
                return ResourceManager.GetString("On_date_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Complaints.
        /// </summary>
        public static string Open_Complaints {
            get {
                return ResourceManager.GetString("Open_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tickets.
        /// </summary>
        public static string Open_Tickets {
            get {
                return ResourceManager.GetString("Open_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayScale Type.
        /// </summary>
        public static string Payscale_Type {
            get {
                return ResourceManager.GetString("Payscale_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        public static string Phone_No {
            get {
                return ResourceManager.GetString("Phone_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill comment field.
        /// </summary>
        public static string Please_fill_comment_field {
            get {
                return ResourceManager.GetString("Please_fill_comment_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select StartDate And EndDate.
        /// </summary>
        public static string Please_Select_StartDate_And_EndDate {
            get {
                return ResourceManager.GetString("Please_Select_StartDate_And_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position List.
        /// </summary>
        public static string Position_list {
            get {
                return ResourceManager.GetString("Position_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorities.
        /// </summary>
        public static string Priorities {
            get {
                return ResourceManager.GetString("Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Id.
        /// </summary>
        public static string Priority_Id {
            get {
                return ResourceManager.GetString("Priority_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority List.
        /// </summary>
        public static string priority_list {
            get {
                return ResourceManager.GetString("priority_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Name.
        /// </summary>
        public static string priority_name {
            get {
                return ResourceManager.GetString("priority_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering User.
        /// </summary>
        public static string Registering_User {
            get {
                return ResourceManager.GetString("Registering_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Tickets.
        /// </summary>
        public static string Rejected_Tickets {
            get {
                return ResourceManager.GetString("Rejected_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion List.
        /// </summary>
        public static string Religion_List {
            get {
                return ResourceManager.GetString("Religion_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY DEPARTMENT.
        /// </summary>
        public static string Report_by_Department {
            get {
                return ResourceManager.GetString("Report_by_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY ESCALATION.
        /// </summary>
        public static string Report_by_Escalation {
            get {
                return ResourceManager.GetString("Report_by_Escalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY FEEDBACK SOURCE.
        /// </summary>
        public static string Report_by_feedback_source {
            get {
                return ResourceManager.GetString("Report_by_feedback_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY FEEDBACK TYPE.
        /// </summary>
        public static string Report_by_feedback_type {
            get {
                return ResourceManager.GetString("Report_by_feedback_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY LAST 12 MONTHS.
        /// </summary>
        public static string Report_by_Last_12_Months {
            get {
                return ResourceManager.GetString("Report_by_Last_12_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY MOST FREQUENT COMPLAINTS.
        /// </summary>
        public static string Report_by_Most_Frequent_Complaints {
            get {
                return ResourceManager.GetString("Report_by_Most_Frequent_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY MOST FREQUENT LOCATIONS.
        /// </summary>
        public static string Report_by_Most_Frequent_Locations {
            get {
                return ResourceManager.GetString("Report_by_Most_Frequent_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY NATIONALITY.
        /// </summary>
        public static string Report_by_Nationality {
            get {
                return ResourceManager.GetString("Report_by_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY POSITION.
        /// </summary>
        public static string Report_by_Position {
            get {
                return ResourceManager.GetString("Report_by_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY REGION.
        /// </summary>
        public static string Report_by_region {
            get {
                return ResourceManager.GetString("Report_by_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY SALARY ISSUES REASON.
        /// </summary>
        public static string Report_by_Salary_Issues_Reason {
            get {
                return ResourceManager.GetString("Report_by_Salary_Issues_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY SATISFACTION.
        /// </summary>
        public static string Report_by_Satisfaction {
            get {
                return ResourceManager.GetString("Report_by_Satisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT BY STATUS.
        /// </summary>
        public static string Report_by_status {
            get {
                return ResourceManager.GetString("Report_by_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string Resolve {
            get {
                return ResourceManager.GetString("Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved Complaints.
        /// </summary>
        public static string Resolved_Complaints {
            get {
                return ResourceManager.GetString("Resolved_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responded Complaints.
        /// </summary>
        public static string Responded_Complaints {
            get {
                return ResourceManager.GetString("Responded_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Time(Hrs).
        /// </summary>
        public static string Response_time {
            get {
                return ResourceManager.GetString("Response_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.No.
        /// </summary>
        public static string S_No {
            get {
                return ResourceManager.GetString("S_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        public static string Salutation {
            get {
                return ResourceManager.GetString("Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfaction.
        /// </summary>
        public static string Satisfaction {
            get {
                return ResourceManager.GetString("Satisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfied.
        /// </summary>
        public static string Satisfied {
            get {
                return ResourceManager.GetString("Satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your Tickets.
        /// </summary>
        public static string Search_your_Tickets {
            get {
                return ResourceManager.GetString("Search_your_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second  Escalation User.
        /// </summary>
        public static string second_escalation_user {
            get {
                return ResourceManager.GetString("second_escalation_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string Select_Category {
            get {
                return ResourceManager.GetString("Select_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        public static string Select_Department {
            get {
                return ResourceManager.GetString("Select_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Job Title.
        /// </summary>
        public static string Select_Job_Title {
            get {
                return ResourceManager.GetString("Select_Job_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        public static string Select_Location {
            get {
                return ResourceManager.GetString("Select_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Nationality.
        /// </summary>
        public static string Select_Nationality {
            get {
                return ResourceManager.GetString("Select_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Position.
        /// </summary>
        public static string Select_Position {
            get {
                return ResourceManager.GetString("Select_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select priority.
        /// </summary>
        public static string Select_priority {
            get {
                return ResourceManager.GetString("Select_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub Location.
        /// </summary>
        public static string Select_Sub_Location {
            get {
                return ResourceManager.GetString("Select_Sub_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        public static string Select_Type {
            get {
                return ResourceManager.GetString("Select_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue.
        /// </summary>
        public static string Sign_in_to_continue {
            get {
                return ResourceManager.GetString("Sign_in_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Sign_up {
            get {
                return ResourceManager.GetString("Sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Fields are  empty.
        /// </summary>
        public static string Some_Fields_are_empty {
            get {
                return ResourceManager.GetString("Some_Fields_are_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string Sub_Category {
            get {
                return ResourceManager.GetString("Sub_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Location.
        /// </summary>
        public static string Sub_Location {
            get {
                return ResourceManager.GetString("Sub_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublocation List.
        /// </summary>
        public static string Sublocation_list {
            get {
                return ResourceManager.GetString("Sublocation_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublocation Name.
        /// </summary>
        public static string Sublocation_name {
            get {
                return ResourceManager.GetString("Sublocation_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        public static string Terminated {
            get {
                return ResourceManager.GetString("Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Escalation User.
        /// </summary>
        public static string third_escalation_user {
            get {
                return ResourceManager.GetString("third_escalation_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Ticket is not found,Try with proper data.
        /// </summary>
        public static string This_Ticket_is_not_found_Try_with_proper_data {
            get {
                return ResourceManager.GetString("This_Ticket_is_not_found_Try_with_proper_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket cannot be forwarded,Escalation User is not assigned.
        /// </summary>
        public static string Ticket_cannot_be_forwarded_Escalation_User_is_not_assigned {
            get {
                return ResourceManager.GetString("Ticket_cannot_be_forwarded_Escalation_User_is_not_assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket created Successfully.
        /// </summary>
        public static string Ticket_created_Successfully {
            get {
                return ResourceManager.GetString("Ticket_created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Detail.
        /// </summary>
        public static string Ticket_Detail {
            get {
                return ResourceManager.GetString("Ticket_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket details are not valid,Fill details properly.
        /// </summary>
        public static string Ticket_details_are_not_valid_Fill_details_properly {
            get {
                return ResourceManager.GetString("Ticket_details_are_not_valid_Fill_details_properly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket has been Closed Successfully.
        /// </summary>
        public static string Ticket_has_been_Closed_Successfully {
            get {
                return ResourceManager.GetString("Ticket_has_been_Closed_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket has been created Successfully.
        /// </summary>
        public static string Ticket_has_been_created_Successfully {
            get {
                return ResourceManager.GetString("Ticket_has_been_created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket has been Rejected.
        /// </summary>
        public static string Ticket_has_been_Rejected {
            get {
                return ResourceManager.GetString("Ticket_has_been_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket has been Resolved Successfully.
        /// </summary>
        public static string Ticket_has_been_Resolved_Successfully {
            get {
                return ResourceManager.GetString("Ticket_has_been_Resolved_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket has been Updated Successfully.
        /// </summary>
        public static string Ticket_has_been_Updated_Successfully {
            get {
                return ResourceManager.GetString("Ticket_has_been_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Id.
        /// </summary>
        public static string Ticket_Id {
            get {
                return ResourceManager.GetString("Ticket_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket List.
        /// </summary>
        public static string Ticket_List {
            get {
                return ResourceManager.GetString("Ticket_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Title.
        /// </summary>
        public static string Ticket_Title {
            get {
                return ResourceManager.GetString("Ticket_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string Type_name {
            get {
                return ResourceManager.GetString("Type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing something.
        /// </summary>
        public static string Typing_something {
            get {
                return ResourceManager.GetString("Typing_something", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        public static string Update_user {
            get {
                return ResourceManager.GetString("Update_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password wrong.
        /// </summary>
        public static string Username_or_Password_wrong {
            get {
                return ResourceManager.GetString("Username_or_Password_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor List.
        /// </summary>
        public static string Vendor_list {
            get {
                return ResourceManager.GetString("Vendor_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string View_Profile {
            get {
                return ResourceManager.GetString("View_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ticket.
        /// </summary>
        public static string View_Ticket {
            get {
                return ResourceManager.GetString("View_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string Welcome_back {
            get {
                return ResourceManager.GetString("Welcome_back", resourceCulture);
            }
        }
    }
}
